import requests
import json

produits = [
    "Polenta semoule de maïs fine Priméal 500g",
    "Riz Basmati complet BIO Priméal 5 kg",
    "Duo de quinoa blanc et rouge Priméal 500g",
    "Fèves en bocal Priméal 215g",
    "Quinoa rouge Priméal en vrac",
    "Riz thai demi complet Priméal en vrac",
    "Riz long blanc Camargue Priméal en vrac",
    "Boulgour d'épeautre Priméal 400G",
    "Couscous complet Priméal en vrac",
    "Quinoa en vrac Priméal",
    "Riz Basmati blanc Priméal en vrac",
    "Riz Basmati demi complet Priméal en vrac",
    "Spirales blanches FF Priméal en vrac",
    "Riz thai blanc Priméal en vrac",
    "Coquillettes blanches Italie Priméal 500g",
    "Haricots beurre extra fins Priméal 720ML",
    "Gingembre confit enrobé de chocolat noir Pronatura en vrac",
    "Pur jus de cranberry BIO Prosain 1L",
    "Pur Jus de Myrtilles BIO Prosain 50CL",
    "Copeaux de noix de coco Rapunzel 175g",
    "Bâtonnets de gingembre confit Rapunzel 75g",
    "Dattes Deglet Nour Rapunzel 500g",
    "Figues séchées Garland Rapunzel 500g",
    "Pépites de chocolat noir Rapunzel en vrac",
    "Bouillon de légumes sans levure Rapunzel 80g",
    "Levure boulangère déshydratée Rapunzel 9g",
    "Feuilles de vigne au riz Rapunzel 280g",
    "Crozets au blé nature Markal 500g",
    "Crozets sarrasin Markal 500g",
    "Macaronis demi complets Markal 500g",
    "Vermicelles demi complètes Markal 500G",
    "Coquillettes blanches Markal 500g",
    "Spaghetti demi complets Markal 500g",
    "Lait de coco Markal 40cl",
    "Marrons entiers naturel Markal 210g",
    "Levure maltée paillettée Markal 250g",
    "Levure maltée Markal en vrac",
    "Son d'avoine Markal 500g",
    "Flocons d'avoine gros Markal 500g",
    "Flocons 5 céréales Markal 500g",
    "Muesli gourmand Markal 500g",
    "Après shampoing réparation Herbatint 200ml",
    "Après shampoing royal Herbatint 200ml",
    "Masque reconstituant Herbatint 200ml",
    "Après shampoing cheveux bouclés Herbatint 200ml",
    "Après-shampoing hydratation Herbatint 200ml",
    "Coloration permanente 3N châtain foncé Herbatint 170ml",
    "Coloration permanente 4N châtain Herbatint 170ml",
    "Coloration permanente 5C châtain clair cendré Herbatint 170ml",
    "Coloration permanente 4M châtain acajou Herbatint 170ml",
    "Coloration permanente 10C blond platine cendré Herbatint 170ml",
    "Coloration permanente 7D blond doré Herbatint 170ml",
    "Coloration permanente 7M blond acajou Herbatint 170ml",
    "Coloration permanente 7C blond cendré Herbatint 170ml",
    "Purée pomme fruits rouges Danival 4x100g",
    "Purée pomme framboise Danival 4x100g",
    "Purée pomme pêche Danival 4x100g",
    "Purée de pomme figue Danival 700g",
    "Purée pommes myrtille Danival 4x100g",
    "Purée pomme vanille Dani'Pom Danival 1,05kg",
    "Taboulé du moulin Danival 620g",
    "Tortillas de blé nature Danival x4",
    "Miso blanc Danival 200g",
    "Miso orge mugi Danival 200g",
    "Marrons entiers Danival 320g",
    "Coloration Douss Color 110 blond clair ultime Beliflor",
    "Coloration Douss Color 101 ebène profond Beliflor",
    "Coloration Douss Color 125 blond doré Beliflor",
    "Coloration Douss Color 141 noisette cuivre Beliflor",
    "Masque nutrition Beliflor 150ml",
    "Bain Capillaire Equilibrant 250 Ml - Beliflor",
    "Masque capillaire restructurant Beliflor 15CL",
    "Coloration Douss Color 117 châtain doré clair Beliflor",
    "Coloration Douss Color 103 brun ultime Beliflor",
    "Baume magique Beliflor 30ml",
    "Lotion capillaire anti-chute Beliflor",
    "Couleur Caramel pour cheveux Beliflor",
    "Couleur Blond Doré pour cheveux Beliflor 135ML",
    "Couleur Blond Moyen pour cheveux Beliflor",
    "Eau de roche N°27 fleur de bach Bio Floral 20ml",
    "Églantier N°37 fleur de bach Bio Floral 20ml",
    "Chèvrefeuille N°16 fleur de bach Bio Floral 20ml",
    "Huile d'olive fruitée médium Bio Planète 50cl",
    "Huile de colza et d'olive Bio Planète 1L",
    "Huile de lin Bio Planète 20cl",
    "Huile pizza et pâtes extra fine Bio Planète 25cl",
    "Huile de coco vierge Bio Planète 950ml",
    "Préparation Falafel Sans Gluten La Ferme Biologique 160G",
    "Minis calissons traditionnels 48g",
    "Pecorino romano dop râpé Argiola 50G",
    "Cookies chocolat amandes sans gluten Nature et cie 150g",
    "Biosoy nature",
    "Vin blanc chardonnay AOP Saint-Véran Cerço 75cl",
    "Vin blanc chardonnay AOP Mâcon Village Cerço 75cl",
    "Vin blanc aligoté AOP Bourgogne Cerço 75cl",
    "Vin blanc Vionnier IGP Pays d'Oc Secret de Lunès 75cl",
    "Vin rouge pinot noir IGP Pays d'Oc Secret de Lunès 75cl",
    "Beurre de baratte moulé doux Tante Hélène 125g",
    "Lait de vache UHT demi-écrémé Natur Avenir 50cl",
]

for desc in produits:
    r = requests.post("http://localhost:11434/api/generate", json={
        "model": "extracteur-produit-v2",
        "prompt": desc,
        "stream": False,
        "format": "json",
    })
    result = json.loads(r.json()["response"])
    print(f"IN : {desc}")
    print(f"OUT: {json.dumps(result, ensure_ascii=False)}")
    print("---")
